POST http://localhost:4004/odata/v4/admin/Users
Authorization: Basic Alice:4Ld1
Content-Type: application/json

{
  "fullName": "Roland the Emperor",
  "originPlanet": "Endor",
  "stardustCollection": 54,
  "wormholeNavigationSkill": 9000,
  "spacesuitColour": "Blue",
  "department_ID": "1",
  "position_ID": "2"
}